"""Generate the Touch Deck's anti-aliased bitmap fonts (aa_fonts.h / aa_fonts.c).

Renders printable ASCII from the design's real typefaces (Barlow, JetBrains
Mono; SIL Open Font License, files in tools/fonts/) at exact pixel sizes into
4-bit alpha glyphs that gfx_text_aa() blends onto the framebuffer.

    python tools/fontgen.py      writes esp32c3/src/aa_fonts.* and src/aa_fonts.*
"""
import os
from collections import namedtuple

from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
FIRST, LAST = 32, 126

FontSpec = namedtuple("FontSpec", "name file size weight use")
FONTS = [
    FontSpec("font_title", "Barlow-SemiBold.ttf", 14, None, "screen titles, host name"),
    FontSpec("font_label", "Barlow-SemiBold.ttf", 12, None, "status lines, row titles"),
    FontSpec("font_button", "Barlow-Bold.ttf", 12, None, "buttons, toggle segments"),
    FontSpec("font_body", "Barlow-Medium.ttf", 10, None, "captions, meta and stats lines"),
    FontSpec("font_caps", "Barlow-Bold.ttf", 9, None, "chip and small-caps labels (spacing 1)"),
    FontSpec("font_big", "Barlow-Bold.ttf", 26, None, "jiggler ON / OFF"),
    FontSpec("font_mono", "JetBrainsMono[wght].ttf", 10, 500, "clip preview"),
    FontSpec("font_pin", "JetBrainsMono[wght].ttf", 17, 500, "pairing PIN digits"),
]

Glyph = namedtuple("Glyph", "w h x y adv alpha")   # x,y: offset from pen / line top
Font = namedtuple("Font", "spec glyphs line ascent cap_top cap_h")


def load_pil(spec):
    f = ImageFont.truetype(os.path.join(HERE, "fonts", spec.file), spec.size,
                           layout_engine=ImageFont.Layout.BASIC)
    if spec.weight is not None:
        f.set_variation_by_axes([spec.weight])
    return f


def render_font(spec):
    pil = load_pil(spec)
    ascent, descent = pil.getmetrics()
    glyphs = {}
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        l, t, r, b = pil.getbbox(ch, anchor="ls")          # relative to pen + baseline
        adv = round(pil.getlength(ch))
        w, h = max(0, r - l), max(0, b - t)
        alpha = []
        if w and h:
            img = Image.new("L", (w, h), 0)
            ImageDraw.Draw(img).text((-l, -t), ch, font=pil, fill=255, anchor="ls")
            alpha = [round(v * 15 / 255) for v in img.getdata()]
        glyphs[ch] = Glyph(w, h, l, ascent + t, adv, alpha)
    _, ht, _, hb = pil.getbbox("H", anchor="ls")
    return Font(spec, glyphs, ascent + descent, ascent, ascent + ht, hb - ht)


def pack4(alpha, w, h):
    out = bytearray()
    for y in range(h):
        row = alpha[y * w:(y + 1) * w]
        for i in range(0, w, 2):
            hi = row[i]
            lo = row[i + 1] if i + 1 < w else 0
            out.append((hi << 4) | lo)
    return bytes(out)


def unpack4(data, w, h):
    alpha, bpr = [], (w + 1) // 2
    for y in range(h):
        for x in range(w):
            byte = data[y * bpr + x // 2]
            alpha.append(byte >> 4 if x % 2 == 0 else byte & 0x0F)
    return alpha


def text_width(font, s, spacing=0):
    if not s:
        return 0
    g = font.glyphs
    return sum(g.get(c, g["?"]).adv for c in s) + spacing * (len(s) - 1)


HEADER = """// Generated by tools/fontgen.py from tools/fonts/ (SIL Open Font License). Do not edit.
#pragma once
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    uint32_t offset;            // into the font's bitmap
    uint8_t w, h;               // bitmap size
    int8_t x, y;                // offset from the pen position / top of the line
    uint8_t adv;                // pen advance
} aa_glyph_t;

typedef struct {
    const uint8_t *bitmap;      // 4-bit alpha, two pixels per byte, rows padded to a byte
    const aa_glyph_t *glyphs;   // ' ' .. '~'
    uint8_t line, ascent;       // line height; baseline offset from the line top
    uint8_t cap_top, cap_h;     // capital-letter band (for vertical centring)
} aa_font_t;

"""


def emit_c(fonts):
    h = [HEADER]
    c = ['// Generated by tools/fontgen.py from tools/fonts/ (SIL Open Font License). Do not edit.\n',
         '#include "aa_fonts.h"\n']
    for f in fonts:
        s = f.spec
        h.append(f"extern const aa_font_t {s.name};   // {s.file} {s.size}px: {s.use}\n")
        bits, table = bytearray(), []
        for code in range(FIRST, LAST + 1):
            g = f.glyphs[chr(code)]
            table.append(f"    {{{len(bits)}, {g.w}, {g.h}, {g.x}, {g.y}, {g.adv}}},  // {chr(code)!r}")
            bits += pack4(g.alpha, g.w, g.h)
        hexes = ", ".join(f"0x{b:02X}" for b in bits)
        c.append(f"\nstatic const uint8_t {s.name}_bits[{len(bits)}] = {{{hexes}}};\n")
        c.append(f"static const aa_glyph_t {s.name}_glyphs[{LAST - FIRST + 1}] = {{\n" + "\n".join(table) + "\n};\n")
        c.append(f"const aa_font_t {s.name} = {{{s.name}_bits, {s.name}_glyphs, {f.line}, {f.ascent}, "
                 f"{f.cap_top}, {f.cap_h}}};\n")
    h.append('\n#ifdef __cplusplus\n}\n#endif\n')
    return "".join(h), "".join(c)


def main():
    fonts = [render_font(s) for s in FONTS]
    header, source = emit_c(fonts)
    for d in ("esp32c3/src", "src"):
        for name, text in (("aa_fonts.h", header), ("aa_fonts.c", source)):
            with open(os.path.join(ROOT, d, name), "w", encoding="utf-8", newline="\n") as fh:
                fh.write(text)
    total = sum(len(pack4(g.alpha, g.w, g.h)) for f in fonts for g in f.glyphs.values())
    print(f"wrote aa_fonts.[ch] to esp32c3/src and src: {len(fonts)} fonts, {total} bitmap bytes")


if __name__ == "__main__":
    main()
