"""Letter lanes for the jiggler: one source for both firmwares and the Windows app.

    python tools/jigpaths.py        # writes src/, esp32c3/src/ and the app's JigPaths.g.cs

Each letter is a centre-line polyline in a unit box (y down) plus a closed flag.
Closed letters loop; open ones bounce back at their ends. H and X retrace their
middle so every letter is one continuous path. Points are emitted in 0..1000
"box units"; each board maps that box onto its screen (BOARDS below).
"""
import math
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

WANDER = 30.0          # box units: max sideways offset of the dot inside the lane
PX_PER_UNIT = 0.12     # mouse px per box unit at 1x (1000 units ~ 120 px)

# Screen geometry of the centre-line box per board (px): x, y, size, lane, wall, dot radius.
BOARDS = {
    "rp2040": dict(dir="src", box_x=71, box_y=91, box=98, lane=18.0, wall=2.0, dot=5.5, w=240, h=280),
    "esp32c3": dict(dir="esp32c3/src", box_x=82, box_y=77, box=76, lane=16.0, wall=2.0, dot=5.0, w=240, h=240),
}


def arc(cx, cy, rx, ry, a0, a1, n):
    return [(cx + rx * math.cos(math.radians(a0 + (a1 - a0) * i / n)),
             cy + ry * math.sin(math.radians(a0 + (a1 - a0) * i / n))) for i in range(n + 1)]


LETTERS = [   # (name, points in a unit box, closed)
    ("O", arc(.5, .5, .5, .5, 0, 360, 48)[:-1], True),
    ("W", [(0, 0), (.22, 1), (.5, .38), (.78, 1), (1, 0)], False),
    ("M", [(0, 1), (0, 0), (.5, .62), (1, 0), (1, 1)], False),
    ("N", [(0, 1), (0, 0), (1, 1), (1, 0)], False),
    ("Z", [(0, 0), (1, 0), (0, 1), (1, 1)], False),
    ("X", [(0, 0), (1, 1), (.5, .5), (1, 0), (0, 1)], False),
    ("C", arc(.55, .5, .45, .5, -45, -315, 36), False),
    ("V", [(0, 0), (.5, 1), (1, 0)], False),
    ("H", [(0, 0), (0, 1), (0, .5), (1, .5), (1, 0), (1, 1)], False),
    ("J", [(.3, 0), (.75, 0), (.75, .68)] + arc(.45, .68, .3, .32, 0, 180, 16)[1:], False),
    ("L", [(0, 0), (0, 1), (1, 1)], False),
    ("B", [(0, .5), (0, 0), (.55, 0)] + arc(.55, .25, .4, .25, -90, 90, 12)[1:] + [(0, .5), (0, 1), (.6, 1)]
     + arc(.6, .75, .4, .25, 90, -90, 12)[1:], True),
    ("G", arc(.55, .5, .45, .5, -40, -360, 40) + [(.55, .5)], False),
    ("D", [(0, 0), (0, 1), (.45, 1)] + arc(.45, .5, .55, .5, 90, -90, 20)[1:], True),
]


def units(pts):
    """Unit box -> integer box units, clamped into 0..1000."""
    return [(max(0, min(1000, round(x * 1000))), max(0, min(1000, round(y * 1000)))) for x, y in pts]


def segments(pts, closed):
    segs = list(zip(pts, pts[1:]))
    if closed:
        segs.append((pts[-1], pts[0]))
    return segs


def cumulative(pts, closed):
    cum = [0.0]
    for a, b in segments(pts, closed):
        cum.append(cum[-1] + math.dist(a, b))
    return cum


def letters():
    """[(name, int points, closed, cumulative lengths)] in LETTERS order."""
    out = []
    for name, pts, closed in LETTERS:
        p = units(pts)
        out.append((name, p, closed, cumulative(p, closed)))
    return out


def c_header(board, round_switch=False):
    """round_switch: the RP tree's header, which hands a TD_ROUND build (the RP2350
    round board) the round layout in src/round/ instead."""
    head = "// Generated by tools/jigpaths.py - do not edit. Letter lanes for the jiggler.\n#pragma once\n"
    if round_switch:
        return head + '#ifdef TD_ROUND\n#include "round/jig_paths.h"\n#else\n' + c_body(board) + "#endif\n"
    return head + c_body(board)


def c_body(board):
    g = BOARDS[board]
    return f"""#include <stdint.h>
#ifdef __cplusplus
extern "C" {{
#endif
typedef struct {{
    char name;
    uint8_t closed;          // 1 = loops, 0 = bounces at the ends
    uint8_t n;               // points
    const int16_t (*pts)[2]; // centre-line points, 0..1000 box units
    const float *cum;        // cumulative length at each segment start (+ total at the end)
    float len;
}} jig_path_t;
extern const jig_path_t JIG_PATHS[];
#define JIG_PATH_COUNT {len(LETTERS)}
#define JIG_WANDER {WANDER:.1f}f
#define JIG_PX_PER_UNIT {PX_PER_UNIT}f
// This board's screen geometry for the centre-line box (px).
#define JIG_BOX_X {g['box_x']}
#define JIG_BOX_Y {g['box_y']}
#define JIG_BOX {g['box']}
#define JIG_LANE {g['lane']:.1f}f
#define JIG_WALL {g['wall']:.1f}f
#define JIG_DOT {g['dot']:.1f}f
#ifdef __cplusplus
}}
#endif
"""


def c_source():
    out = ["// Generated by tools/jigpaths.py - do not edit.", '#include "jig_paths.h"', ""]
    for name, p, closed, cum in letters():
        out.append(f"static const int16_t P_{name}[][2] = {{" + ", ".join(f"{{{x},{y}}}" for x, y in p) + "};")
        out.append(f"static const float C_{name}[] = {{" + ", ".join(f"{c:.1f}f" for c in cum) + "};")
    out.append("")
    out.append("const jig_path_t JIG_PATHS[] = {")
    for name, p, closed, cum in letters():
        out.append(f"    {{'{name}', {int(closed)}, {len(p)}, P_{name}, C_{name}, {cum[-1]:.1f}f}},")
    out.append("};")
    return "\n".join(out) + "\n"


def cs_source():
    rows = []
    for name, p, closed, _ in letters():
        pts = ", ".join(f"({x}, {y})" for x, y in p)
        rows.append(f"        new('{name}', {'true' if closed else 'false'}, [{pts}]),")
    return f"""// Generated by tools/jigpaths.py - do not edit.
#nullable enable
namespace TouchDeck.Core.Jiggler;

/// <summary>A jiggler letter: centre-line points in 0..1000 box units; closed letters loop.</summary>
public sealed record JigLetter(char Name, bool Closed, (short X, short Y)[] Points);

public static class JigPaths
{{
    public static IReadOnlyList<JigLetter> All {{ get; }} =
    [
{chr(10).join(rows)}
    ];

    public static JigLetter? Find(char name) => All.FirstOrDefault(l => l.Name == name);
}}
"""


def outputs():
    """{path: text} of every generated file."""
    files = {}
    for board, g in BOARDS.items():
        files[os.path.join(ROOT, g["dir"], "jig_paths.h")] = c_header(board, round_switch=board == "rp2040")
        files[os.path.join(ROOT, g["dir"], "jig_paths.c")] = c_source()
    # The RP2350 round board shares the RP tree but the ESP32-C3's round layout.
    files[os.path.join(ROOT, "src", "round", "jig_paths.h")] = c_header("esp32c3")
    files[os.path.join(ROOT, "windows-app", "src", "TouchDeck.Core", "Jiggler", "JigPaths.g.cs")] = cs_source()
    return files


def main():
    for path, text in outputs().items():
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print("wrote", os.path.relpath(path, ROOT))


if __name__ == "__main__":
    main()
