// Generated by tools/fontgen.py from tools/fonts/ (SIL Open Font License). Do not edit.
// Rendered with Pillow 11.3.0, FreeType 2.13.3
#pragma once
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    uint32_t offset;            // into the font's bitmap
    uint8_t w, h;               // bitmap size
    int8_t x, y;                // offset from the pen position / top of the line
    uint8_t adv;                // pen advance
} aa_glyph_t;

typedef struct {
    const uint8_t *bitmap;      // 4-bit alpha, two pixels per byte, rows padded to a byte
    const aa_glyph_t *glyphs;   // ' ' .. '~'
    uint8_t line, ascent;       // line height; baseline offset from the line top
    uint8_t cap_top, cap_h;     // capital-letter band (for vertical centring)
} aa_font_t;

extern const aa_font_t font_title;   // Barlow-SemiBold.ttf 14px: screen titles, host name
extern const aa_font_t font_label;   // Barlow-SemiBold.ttf 12px: status lines, row titles
extern const aa_font_t font_button;   // Barlow-Bold.ttf 12px: buttons, toggle segments
extern const aa_font_t font_body;   // Barlow-Medium.ttf 10px: captions, meta and stats lines
extern const aa_font_t font_caps;   // Barlow-Bold.ttf 9px: chip and small-caps labels (spacing 1)
extern const aa_font_t font_big;   // Barlow-Bold.ttf 26px: jiggler ON / OFF
extern const aa_font_t font_mono;   // JetBrainsMono[wght].ttf 10px: clip preview
extern const aa_font_t font_pin;   // JetBrainsMono[wght].ttf 17px: pairing PIN digits

#ifdef __cplusplus
}
#endif
