// Generated by tools/jigpaths.py - do not edit. Letter lanes for the jiggler.
#pragma once
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif
typedef struct {
    char name;
    uint8_t closed;          // 1 = loops, 0 = bounces at the ends
    uint8_t n;               // points
    const int16_t (*pts)[2]; // centre-line points, 0..1000 box units
    const float *cum;        // cumulative length at each segment start (+ total at the end)
    float len;
} jig_path_t;
extern const jig_path_t JIG_PATHS[];
#define JIG_PATH_COUNT 14
#define JIG_WANDER 30.0f
#define JIG_PX_PER_UNIT 0.12f
// This board's screen geometry for the centre-line box (px).
#define JIG_BOX_X 71
#define JIG_BOX_Y 91
#define JIG_BOX 98
#define JIG_LANE 18.0f
#define JIG_WALL 2.0f
#define JIG_DOT 5.5f
#ifdef __cplusplus
}
#endif
